### ISSUE TITLE
레시피 카드 제작

### ISSUE THREAD

**Issue by hyobiin9** [2-Docthru-team1/2-Docthru-team1-FE#10]
## 작업 사항 설명
레시피 카드 제작하는 작업입니다.
![image](https://github.com/user-attachments/assets/e222c4d1-386d-42ff-bbf1-df6fe87e3a38)

## TO-DO
- [x] 레시피 카드 컴포넌트 ui
- [x] mock data 연결
- [x] 레시피 리스트 페이지 mapping
- [x] tailwind 적용
