### ISSUE TITLE
챌린지 리스트 페이지 api 연결

### ISSUE THREAD

**Issue by galaxy-78** [2-Docthru-team1/2-Docthru-team1-FE#102]
## 작업 사항 설명
<img width="700" alt="Screenshot 2024-11-23 at 16 51 24" src="https://github.com/user-attachments/assets/603f376f-afe3-4a7e-a1f1-cd1c78b5d87e">

## TO-DO

- [x] 로그인 기능 zustand로 전부 변경
  - usercontext X -> zustand
- [x] userId, role zustand 전역 설정
- [X] 새로고침 했을 때 로그인 풀리지 않게 로컬스토리지에 저장된 데이터 불러오기
- [x] API 연결
- [x] 테스트
- [x] 칩 카테고리 수정
  - 백엔드에서 보내는 글자가 형식에 맞지 않아 맞춰서 출력.
- [x] Cancel 토글 컴포넌트 넣기
  - css 맞추기
  - 모달 아직 안넣음

## 기타
나중 작업 사항
- 접근 권한설정 : url로 접근시 들어가면 안되는 페이지에 들어갈 수 있는 문제 해결하기
- Cancel 토글 컴포넌트 
  - 모달 작업
  - API 연결해서 챌린지 상태 수정하기 cancel
- 이달의 챌린지 및 랭커 카드는 현재 목데이터
  -> API 만들어지면 연결하기
