### ISSUE TITLE
챌린지 신청 페이지 만들기

### ISSUE THREAD

**Issue by galaxy-78** [2-Docthru-team1/2-Docthru-team1-FE#107]
## 작업 사항 설명
<img width="482" alt="Screenshot 2024-11-23 at 21 43 15" src="https://github.com/user-attachments/assets/7b3a70ed-1110-4973-a004-e122486eab9c">

## TO-DO

- [ ] 리퀘스트 버튼 이미지 -> css로 직접 만들기
- [ ] title, recipe link, content input
- [ ] recipe media type 드롭다운 만들기
- [ ] 이미지 넣는 컴포넌트 넣기

## 기타
다음 작업 사항
- 날짜 정하는 드롭다운 만들기
