### ISSUE TITLE
챌린지 리스트 전반적인 수정 (+ 토큰 관련, API 관련)

### ISSUE THREAD

**Issue by galaxy-78** [2-Docthru-team1/2-Docthru-team1-FE#121]
## TO-DO

- [x] url 받아서 이미지 전송 시키기
  - 이전에 push 안됐던 거 적용 (git local 오류)
- [x] 토큰 가져오는 방식 다시 수정하기
- [x] 리스트 status가 onGoing, finished 만 가져오기
- [x] 리스트 개수 -> 페이지네이션
- [x] 챌린지 리스트 - 리스트 비었을 때 만들기

## 기타

다음 작업 사항
- 로컬 스토리지 문제 해결하기
- 챌린지 리스트 sort API 연결
- cancel, abort API 연결
  - id와 매치해서 본인 챌린지에 토글 뜨게 만들기
  - 챌린지status patch - status만 보내도 됨.
  - token 넘겨주어야 함.
