### ISSUE TITLE
로컬 스토리지 충돌 문제 해결

### ISSUE THREAD

**Issue by galaxy-78** [2-Docthru-team1/2-Docthru-team1-FE#126]
## 작업 사항 설명
![Screenshot 2024-11-26 at 17 23 48](https://github.com/user-attachments/assets/e10aab8f-b497-43a6-8197-986d35358c02)

## TO-DO

- [x] 이전 PR 코멘트 적용 시키기
  - true, falsy 사용하기
  - fetch -> axios로 고치기
- [x] 로컬 스토리지 문제 해결하기
- [x] hook 으로 구분함.
  - 속도 개선.

## 기타
- 챌린지 리스트 sort API 연결
  - filterbar css 날아간 문제 해결
- cancel, abort API 연결
  - id와 매치해서 본인 챌린지에 토글 뜨게 만들기 (id를 못불러오는 듯 함)
  - 챌린지status patch - status만 보내도 됨.
  - token 넘겨주어야 함.
