### ISSUE TITLE
내브바 제작

### ISSUE THREAD

**Issue by hyobiin9** [2-Docthru-team1/2-Docthru-team1-FE#14]
## 작업 사항 설명
내브바 제작
![image](https://github.com/user-attachments/assets/db2a19b5-7e8b-42ab-ab7b-cf077e80c725)

## TO-DO

- [x] ui 제작
- [x] 라우터 반영해서 nav바 색상 변경
- [x] status에 따라 nav바 변경
- [x] 번역 모달창 제작
- [x] 모달 컴포넌트 제작
