### ISSUE TITLE
챌린지 페이지 keyword 검색 기능

### ISSUE THREAD

**Issue by galaxy-78** [2-Docthru-team1/2-Docthru-team1-FE#152]
## TO-DO

- [x] keyword 검색 API 작동 되게 하기
  - 엔터 칠때만 검색되도록
- [x] 레시피 드롭다운, 필터바 분리되어 삭제하기
- [x] 필터바 css 수정
- [x] 언어 모달 수정

## 기타
[챌린지 페이지]
- 챌린지 정렬 API CSR -> SSR 로직 변경
- page와pageSize 넘겨주는 거 고려해서 다시 수정하기
- 현재 프론트에서 onGoing, finished로 걸러주고 있는데, 리스트 받아오는데 문제가 생겨서 백엔드 측에서 만들어주면 아래와 같이 수정.
  - 챌린지 리스트 페이지 / 어드민 관리 페이지 두개로 API 나눠서 하기
- 어드민챌린지는 백엔드 API 연결하기
- modal에 abort reason 쓰는 input 집어넣기
  - 그러면 API 바로 작동 가능
