### ISSUE TITLE
챌린지 API 연결 수정 및 Abort 모달 수정

### ISSUE THREAD

**Issue by galaxy-78** [2-Docthru-team1/2-Docthru-team1-FE#162]
## TO-DO

- [x] 현재 프론트에서 onGoing, finished로 걸러주고 있는데, 리스트 받아오는데 문제가 생겨서 백엔드 측에서 만들어주면 아래와 같이 수정.
  - 챌린지 리스트 페이지 / 어드민 관리 페이지 두개로 API 나눠서 하기
- [x] 어드민챌린지는 백엔드 API 연결하기
- [x] modal에 admin일때만 abort reason 쓰는 textarea 만들기
  -  그러면 API 바로 작동 가능

## 기타
[챌린지 페이지]
- 챌린지 정렬 API CSR -> SSR 로직 변경
- page와pageSize 넘겨주는 거 고려해서 다시 수정하기
- 미디어 쿼리 적용하기
[챌린지 신청 페이지]
- 미디어 쿼리 적용하기

[알림]
- 웹 소켓 - socketio react 알림보내주기
  - 공부하기
