### ISSUE TITLE
레시피 카드 컴포넌트 제작

### ISSUE THREAD

**Issue by hyobiin9** [2-Docthru-team1/2-Docthru-team1-FE#2]
## TO-DO

- [x] 레시피 카드 컴포넌트 ui
- [x] mock data 연결
- [ ] 레시피 리스트 페이지 mapping
