### ISSUE TITLE
PUT 메소드 추상화

### ISSUE THREAD

**Issue by galaxy-78** [2-Docthru-team1/2-Docthru-team1-FE#201]
## TO-DO

- [x] PUT 메소드 추상화
- [x] 챌린지 신청 페이지에 적용.
- [ ] 작업물 도전하기 페이지에 적용

### 다음 작업 사항
[유지보수]
- 지속적으로 테스트해서 문제 해결하기
  - css
  - 기능
  - 성능

[챌린지 페이지]
- 챌린지 정렬 API CSR -> SSR 로직 변경
- filtered (숫자) - 2줄 되는거 수정 (미디어쿼리)

[알림]
- 웹 소켓 - socketio react 알림보내주기
  - 공부하기

[라우터]
- 라우터 접근 제한 설정 (권한에 따라)
