### ISSUE TITLE
알림 컴포넌트 제작

### ISSUE THREAD

**Issue by galaxy-78** [2-Docthru-team1/2-Docthru-team1-FE#203]
## 작업 사항 설명
![Screenshot 2024-12-02 at 11 25 14](https://github.com/user-attachments/assets/5bf63c67-5ac4-4f67-a1ce-d23457d1984c)

[[socket.io](http://socket.io/) 실시간 알림]
1. 챌린지가 종료 되었을 때 (onGoing -> finished)
2. 신청한 챌린지가 approved or rejected 되었을 때
  - 거절하면 거절 사유 포함.
3. 내 작업물에 댓글 달렸을 때
4. 내가 참여하고 있는 챌린지에 새로운 작업물이 생길 때
5. 알림 전송 시간 받기

## TO-DO
[알림 드롭다운 컴포넌트]
- [x] 컴포넌트 만들기
- [x] 스토리북 만들기
- [x] 알림 아이콘에 연결하기
- [x] 페이지 이동하면 프로필 모달이랑 알림 모달 닫기게 수정
- [x] createdAt 시간 UTC 시간이라서 한국 시간으로 바꾸기

[웹 소켓 - socketio 알림]
- [x] Client API & 튜토리얼 공부하기 완료

### 다음 작업 사항
[알림 드롭다운 컴포넌트 심화]
- 알림 오면 알림 이미지 옆에 점 생겨서 표시
- 알림 온 거 한번 누르면(확인하면) 표시해주기
- 누르면 관련 페이지로 이동하게

[웹 소켓 - socketio 알림]
- 로그인 할 때 토큰 실시간으로 보내기
- 알림 이벤트 수신

[유지보수]
- 지속적으로 테스트해서 문제 해결하기
  - css
  - 기능
  - 성능

[라우터]
- 라우터 접근 제한 설정 (권한에 따라)
