### ISSUE TITLE
작업물 도전하기 페이지 PUT (git 에러로 재시작)

### ISSUE THREAD

**Issue by galaxy-78** [2-Docthru-team1/2-Docthru-team1-FE#214]
## TO-DO

- [x] 작업물 도전하기 페이지에 적용
- [x] 워크 삭제시 해당 챌린지 페이지로 가게 수정

- [x] embed url 가져오는 걸로 수정하기 (원래 example.com 되어있었음)
  - embed 및 see content 버튼 둘 다 수정
- [x] 새창에서 열리게 만들기
- [x] youtube embed 삽입하기
