### ISSUE TITLE
챌린지 리스트 정렬 SSR 로직 변경

### ISSUE THREAD

**Issue by galaxy-78** [2-Docthru-team1/2-Docthru-team1-FE#216]
## TO-DO
[챌린지 페이지]
- [x] 챌린지 정렬 API CSR -> SSR 로직 변경
- [x] 키워드 비어있을 때, 드롭다운 선택 비어있을 때 새로고침 X -> 그 상태를 검색하도록.
- [x] 필터바 filtered(숫자) 되었을 때 두줄 되는 문제 해결.

### 다음 작업 사항
[유지보수]
- 지속적으로 테스트해서 문제 해결하기
  - css
  - 기능
  - 성능

[라우터]
- 라우터 접근 제한 설정 (권한에 따라) 모든 페이지 하고, 체크 하기
