### ISSUE TITLE
회원가입 페이지 및 레시피 페이지 반응형 에러 수정 & 어드민 유저 마이페이지 접근x

### ISSUE THREAD

**Issue by LDY981212** [2-Docthru-team1/2-Docthru-team1-FE#219]
## TO-DO

- [x] 회원가입 페이지 validation 오류 반응형 수정
- [x] 레시피 페이지 pc버전 grid 순서 수정
- [x]  어드민 유저 마이페이지 접근x
