### ISSUE TITLE
socketio 알림 송수신

### ISSUE THREAD

**Issue by galaxy-78** [2-Docthru-team1/2-Docthru-team1-FE#228]
## 작업 사항 설명
[[socket.io](http://socket.io/) 실시간 알림]
1. 챌린지가 종료 되었을 때 (onGoing -> finished)
2. 신청한 챌린지가 approved or rejected 되었을 때
  - 거절하면 거절 사유 포함.
3. 내 작업물에 댓글 달렸을 때
4. 내가 참여하고 있는 챌린지에 새로운 작업물이 생길 때
5. 알림 전송 시간 받기

## TO-DO
[챌린지 페이지]
- [x] 이달의 랭커 API 연결

[소켓 클라이언트 패키지 설치]
```shell
$ npm install socket.io-client
``` 

[웹 소켓 - socketio 알림]
- [x] 연결 성공 - 서버 CORS 설정 및 http로 변경 (SSL 인증 문제 때문)
- [x] 로그인 할 때 토큰 실시간으로 송신
- [x] 챌린지가 종료 되었을 때 (onGoing -> finished) 알림 수신
- [x] 모달 창 열시, 페이지 새로고침 시 GET API로 데이터 불러오기

[알림 컴포넌트 심화]
- [x] 누르면 관련 페이지로 이동하게
- [x] 알림이 15개가 넘어가면 새로 받아 올때마다 젤 오래된 알람을 지우기

### 다음 작업 사항
[웹 소켓 - socketio 알림]
- 피드백 댓글 알림 수신

[알림 컴포넌트 심화]
- 닫힌 상태에서도 알림이 오면 알림 이미지 옆에 빨간 점 생겨서 표시
- 알림 온 거 확인하면 표시해주기

[유지보수]
- 지속적으로 테스트해서 문제 해결하기
  - css
  - 기능
  - 성능

[라우터]
- 라우터 접근 제한 설정 (권한에 따라)
