### ISSUE TITLE
작업물 수정 페이지

### ISSUE THREAD

**Issue by LDY981212** [2-Docthru-team1/2-Docthru-team1-FE#236]
## TO-DO

- [x] 작업물 수정 기능
- [x] 댓글 에러 해결
- [x] 작업물 페이지 라우터 에러 해결
- [x] 챌린지 상세 페이지 the most liked card 내용 html 삽입
