### ISSUE TITLE
작업물 페이지 작업물 컴포넌트 

### ISSUE THREAD

**Issue by LDY981212** [2-Docthru-team1/2-Docthru-team1-FE#46]
## 작업 사항 설명
![image](https://github.com/user-attachments/assets/245d8f1c-74d7-48d9-ba94-97701900894d)

## TO-DO

- [x] 작업물 컴포넌트 UI
- [x] 이미지 클릭시 확대
- [x] 이미지 넘기기 기능
- [x] 작성한 유저일 때 dropdown 표시
