### ISSUE TITLE
이달의 챌린지 카드 수정, 테스트

### ISSUE THREAD

**Issue by galaxy-78** [2-Docthru-team1/2-Docthru-team1-FE#54]
## 작업 사항 설명
<img width="749" alt="Screenshot 2024-11-19 at 16 45 09" src="https://github.com/user-attachments/assets/01ab5106-bfb9-4e15-9f0b-a20c1bdf8151">

## TO-DO

- [x] 만든 컴포넌트와 칩들을 연결하여 테스트. (ChipCard, ChipCategory)
- [ ] css 도 다시 수정
- [x] 만든 스토리북도 활용하여 테스트.

## 기타

다음 작업 예정
