### ISSUE TITLE
드롭다운 컴포넌트 생성 및 작업물 페이지에 연결

### ISSUE THREAD

**Issue by LDY981212** [2-Docthru-team1/2-Docthru-team1-FE#57]
## 작업 사항 설명
드롭다운 컴포넌트 만든 후 작업물 페이지에서 잘 작동하는지 확인
## TO-DO

- [x] 드롭다운 컴포넌트 제작
- [x] 작업물 페이지에서 정상 작동하는지 확인
- [x] cancel 확인 모달 컴포넌트 제작
- [x] 드롭다운 cancel과 모달 연결
