### ISSUE TITLE
챌린지 보기 페이지

### ISSUE THREAD

**Issue by galaxy-78** [2-Docthru-team1/2-Docthru-team1-FE#68]
## 작업 사항 설명
<img width="852" alt="Screenshot 2024-11-20 at 14 59 32" src="https://github.com/user-attachments/assets/5b6539b7-3841-4dd4-8165-e03aa1ee7060">

## TO-DO
챌린지 보기 페이지 작업
- [x] This Month's Challenge 부분 작업
- [x] Challenge List 부분 작업
- [x] 페이지네이션 넣기
- [x] 필터바 넣기
- [x] 리퀘스트 챌린지 버튼 넣기
- [x] 이달의 랭커 부분 작업
- [x] 만들었던 컴포넌트 css 수정
- [x] 목데이터 삽입 

## 기타
- [x] NAV바 제외하고 배경색 gray-50 적용
- [x] recipeList route 주소에 맞게 challege -> challengeList로 변경
- [x] filterbar css 수정
   - bg-primary-white
   - 배치 수정
   - 가로 길이 수정
