### ISSUE TITLE
sign 인풋 컴포넌트 만들기

### ISSUE THREAD

**Issue by galaxy-78** [2-Docthru-team1/2-Docthru-team1-FE#86]
## 작업 사항 설명

<img width="628" alt="Screenshot 2024-11-22 at 12 21 01" src="https://github.com/user-attachments/assets/66de0b2d-3253-4ef7-aea0-454638b13cf5">

## TO-DO

- [x] 입력창 컴포넌트 만들기
- [x] 비밀번호에만 들어가는 토글 고려하기
- [x] 스토리북으로 테스트 하기

## 기타
- [x] route 주소 signin -> signIn
- [x] 각 컴포넌트 자체에 mb-[2.4rem] 설정
- [x] focus 시 테두리 primary-beige로 설정

- 아래 sign + 글자도 할까 고민
