### ISSUE TITLE
로그인 페이지 만들기

### ISSUE THREAD

**Issue by galaxy-78** [2-Docthru-team1/2-Docthru-team1-FE#92]
## 작업 사항 설명
<img width="671" alt="Screenshot 2024-11-22 at 13 17 16" src="https://github.com/user-attachments/assets/722ebbdb-cfca-44b2-a8d3-80a85f3c4b31">

## TO-DO

- [x] SingInClient.tsx 완성 시키기.
  - 타이틀
  - validation
  - 폼 제출 버튼
  - 버튼 아래 글
- [x] 페이지 연동 - API 연결

## 기타
- [x] token 이용해서 nav바 다루기
  - 로그인 상태 -> 랜딩 페이지 접속 X
  - 일반 유저 로그인 -> 레시피, 챌린지, 번역, 알림, 프로필, 로그아웃
  - 어드민 유저 로그인 -> 레시피, 챌린지, mgmt, 번역, 왕관프로필, 로그아웃
  - css 수정
- [x] 로그아웃 버튼 만들기
  - 토큰 삭제
